version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgresql-local
    volumes:
      - "/var/run/postgres.sock:/var/run/postgres/postgres.sock"
      #- "/home/myuser/docker-apps/volumes/postgres-data:/var/lib/postgresql/data"
      - "c:/postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=mydb1234
  pg_admin:
    image: dpage/pgadmin4:6.1
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=some@email.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - postgres_db